apiVersion: redskyops.dev/v1beta1
kind: Experiment
metadata:
  labels:
    redskyops.dev/application: tvk-backup
  name: tvk-backup
  namespace: default
spec:
  metrics:
  - minimize: true
    name: cost
    port: 9090
    query: ({{ cpuRequests . "app.kubernetes.io/part-of=k8s-triliovault" }} * 1) + ({{ memoryRequests . "app.kubernetes.io/part-of=k8s-triliovault" | GB }} * 1)
    type: prometheus
  - minimize: true
    name: cost-cpu-requests
    optimize: false
    port: 9090
    query: '{{ cpuRequests . "app.kubernetes.io/part-of=k8s-triliovault" }}'
    type: prometheus
  - minimize: true
    name: cost-memory-requests
    optimize: false
    port: 9090
    query: '{{ memoryRequests . "app.kubernetes.io/part-of=k8s-triliovault" | GB }}'
    type: prometheus
  - minimize: true
    name: duration
    port: 0
    query: '{{ duration .StartTime .CompletionTime }}'
  parameters:
  - max: 3
    min: 1
    name: replicas
  - max: 2000
    min: 10
    name: metaCpu
  - max: 10
    min: 2048
    name: metaMemory
  - max: 4092
    min: 10
    name: dataMem  
  - max: 2000
    min: 10
    name: dataCpu     
  trialTemplate:
    metadata:
      labels:
        redskyops.dev/application: tvk-backup
    spec:
      setupServiceAccountName: redsky-setup
      setupTasks:
      - args:
        - prometheus
        - $(MODE)
        name: monitoring
      - name: tvk-manager
        helmChart: k8s-triliovault
        helmChartVersion: 2.0.1
        helmRepository: https://github.com/trilioData/k8s-triliovault
        helmValues:
        - name: replicaCount
          value: "{{ .Values.replicas }}"
        - name: defaultMetaJobLimits.cpu
          value: "{{ .Values.metaCpu }}m"
        - name: defaultMetaJobLimits.memory
          value: "{{ .Values.metaMemory }}Mi"
        - name: defaultDataJobLimits.cpu
          value: "{{ .Values.dataCpu }}m"
        - name: defaultDataJobLimits.memory
          value: "{{ .Values.dataMemory }}Mi"
      jobTemplate:
        spec:
          activeDeadlineSeconds: 4800
          template:
            spec:
              serviceAccount: redsky-setup
              containers:
              - image: bitnami/kubectl:latest
                name: kubectl
                command: ["/scripts/wrapper.sh"]
                ports:
                - name: kubectl
                  containerPort: 2368
                  protocol: TCP
                volumeMounts:
                  - name: wrapper
                    mountPath: /scripts
                  - name: backuptrial
                    mountPath: /manifests
              volumes:
                - name: wrapper
                  configMap:
                    name: wrapper
                    defaultMode: 0755
                - name: backuptrial
                  configMap:
                    name: backuptrial    
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    redskyops.dev/application: tvk-backup
  name: redsky-setup
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    redskyops.dev/application: tvk-backup
  name: redsky-prometheus
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  - configmaps
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    redskyops.dev/application: tvk-backup
  name: redsky-setup-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redsky-prometheus
subjects:
- kind: ServiceAccount
  name: redsky-setup
  namespace: default