apiVersion: redskyops.dev/v1alpha1
kind: Experiment
metadata:
  name: triliovault-experiment
spec:
  optimization:
  - name: "experimentBudget"
    value: "120"
  parameters:
  - name: controlplane_cpu
    min: 1
    max: 100
  - name: controlplane_memory
    min: 10
    max: 256
  - name: exporter_cpu
    min: 1
    max: 100
  - name: exporter_memory
    min: 10
    max: 256
  - name: webhook_cpu
    min: 1
    max: 100
  - name: webhook_memory
    min: 10
    max: 256
  metrics:
  - name: duration
    minimize: true
    query: "{{duration .StartTime .CompletionTime}}"
  - name: cost
    minimize: true
    type: pods
    # Note that these cost weights are specific to GKE and represent $22/month/cpu and $3/month/GB
    query: '{{resourceRequests .Pods "cpu=0.022,memory=0.000000000003"}}'
    selector:
      matchLabels:
        app.kubernetes.io/name: k8s-triliovault
  patches:
  - targetRef:
      kind: Deployment
      apiVersion: apps/v1
      name: k8s-triliovault-control-plane
    patch: |
      spec:
        template:
          spec:
            containers:
            - name: triliovault-control-plane
              resources:
                limits:
                  cpu: "{{ .Values.controlplane_cpu }}m"
                  memory: "{{ .Values.controlplane_memory }}Mi"
                requests:
                  cpu: "{{ .Values.controlplane_cpu }}m"
                  memory: "{{ .Values.controlplane_memory }}Mi"
  - targetRef:
      kind: Deployment
      apiVersion: apps/v1
      name: k8s-triliovault-exporter
    patch: |
      spec:
        template:
          spec:
            containers:
            - name: triliovault-exporter
              resources:
                limits:
                  cpu: "{{ .Values.exporter_cpu }}m"
                  memory: "{{ .Values.exporter_memory }}Mi"
                requests:
                  cpu: "{{ .Values.exporter_cpu }}m"
                  memory: "{{ .Values.exporter_memory }}Mi"
  - targetRef:
         kind: Deployment
         apiVersion: apps/v1
         name: k8s-triliovault-admission-webhook
    patch: |
      spec:
        template:
          spec:
            containers:
            - name: triliovault-admission-webhook
              resources:
              limits:
                  cpu: "{{ .Values.webhook_cpu }}m"
                  memory: "{{ .Values.webhook_memory }}Mi"
                requests:
                  cpu: "{{ .Values.webhook_cpu }}m"
                  memory: "{{ .Values.webhook_memory }}Mi"                
  template: # trial
    spec:
      ttlSecondsAfterFinished: 1800
      setupServiceAccountName: redsky
      template: # job
        spec:
          template: # pod
            spec:
              activeDeadlineSeconds: 1800
              containers:
              - image: bitnami/kubectl:latest
                name: kubectl
                command: ["/scripts/wrapper.sh"]
                ports:
                - name: kubectl
                  containerPort: 2368
                  protocol: TCP
                volumeMounts:
                  - name: wrapper
                    mountPath: /scripts
                  - name: backuptrial
                    mountPath: /manifests  
              volumes:
                - name: wrapper
                  configMap:
                    name: wrapper
                    defaultMode: 0755
                - name: backuptrial
                  configMap:
                    name: backuptrial    
