apiVersion: apps.redskyops.dev/v1alpha1
kind: Application
metadata:
  name: tvk-backup

resources:

parameters:
  containerResources:
    labelSelector: app.kubernetes.io/part-of=k8s-triliovault
  replicas:
    labelSelector: app.kubernetes.io/part-of=k8s-triliovault

objectives:
- name: cost
  requests:
    metricSelector: app.kubernetes.io/part-of=k8s-triliovault
- name: duration 

