apiVersion: redskyops.dev/v1beta1
kind: Experiment
metadata:
  labels:
    redskyops.dev/application: tvk-backup
  name: tvk-backup
  namespace: default
spec:
  metrics:
  - minimize: true
    name: cost
    port: 9090
    query: ({{ cpuRequests . "app.kubernetes.io/part-of=k8s-triliovault" }} * 1) + ({{ memoryRequests . "app.kubernetes.io/part-of=k8s-triliovault" | GB }} * 1)
    type: prometheus
  - minimize: true
    name: cost-cpu-requests
    optimize: false
    port: 9090
    query: '{{ cpuRequests . "app.kubernetes.io/part-of=k8s-triliovault" }}'
    type: prometheus
  - minimize: true
    name: cost-memory-requests
    optimize: false
    port: 9090
    query: '{{ memoryRequests . "app.kubernetes.io/part-of=k8s-triliovault" | GB }}'
    type: prometheus
  - minimize: true
    name: duration
    port: 0
    query: '{{ duration .StartTime .CompletionTime }}'
  parameters:
  - baseline: 11
    max: 4096
    min: 128
    name: memory
  - baseline: 10
    max: 4000
    min: 100
    name: cpu
  - baseline: 1
    max: 5
    min: 1
    name: replicas
  patches:
  - patch: |
      spec:
        replicas: {{ .Values.replicas }}
        template:
          spec:
            containers:
            - name: ingress-controller
              resources:
                limits:
                  memory: '{{ .Values.memory }}M'
                  cpu: '{{ .Values.cpu }}m'
                requests:
                  memory: '{{ .Values.memory }}M'
                  cpu: '{{ .Values.cpu }}m'
    targetRef:
      apiVersion: apps/v1
      kind: Deployment
      name: k8s-triliovault-ingress-controller
      namespace: default
  trialTemplate:
    metadata:
      labels:
        redskyops.dev/application: tvk-backup
    spec:
      setupServiceAccountName: redsky-setup
      setupTasks:
      - args:
        - prometheus
        - $(MODE)
        name: monitoring
---
apiVersion: v1
kind: ServiceAccount
metadata:
  labels:
    redskyops.dev/application: tvk-backup
  name: redsky-setup
  namespace: default
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    redskyops.dev/application: tvk-backup
  name: redsky-prometheus
rules:
- apiGroups:
  - rbac.authorization.k8s.io
  resources:
  - clusterroles
  - clusterrolebindings
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - ""
  resources:
  - serviceaccounts
  - services
  - configmaps
  verbs:
  - get
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  verbs:
  - get
  - create
  - delete
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - nodes
  - nodes/metrics
  - nodes/proxy
  - services
  verbs:
  - list
  - watch
  - get
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  labels:
    redskyops.dev/application: tvk-backup
  name: redsky-setup-prometheus
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: redsky-prometheus
subjects:
- kind: ServiceAccount
  name: redsky-setup
  namespace: default
---
