apiVersion: v1
kind: ServiceAccount
metadata:
  name: redsky
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: triliovault-setup
rules:
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - configmaps
  - serviceaccounts
  - services
  verbs:
  - create
  - delete
- apiGroups:
  - apps
  resources:
  - deployments
  - statefulsets
  verbs:
  - create
  - delete
- apiGroups:
  - triliovault.trilio.io
  resources: 
  - backup
  verbs:
  - create
  - delete
  - list
  - watch
  - get
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: redsky-triliovault-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: triliovault-setup
subjects:
- kind: ServiceAccount
  name: redsky
  namespace: default